apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.12.2
          ports:
            - containerPort: 5601
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic.svc.cluster.local:9200"
            - name: SERVER_PUBLICBASEURL
              value: "http://localhost:5601"

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30001
  type: NodePort