input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["belt-data"]
    group_id => "belt-logstash-group"
    codec => "json"
    auto_offset_reset => "earliest"
    decorate_events => true
  }
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["belt-predictions"]
    group_id => "belt-predictions-logstash-group"
    codec => "json"
    auto_offset_reset => "earliest"
    decorate_events => true
  }
}

filter {
  if [@metadata][kafka][topic] == "belt-data" {
    mutate {
      add_field => { "pipeline" => "belt-raw-data" }
    }
  } else if [@metadata][kafka][topic] == "belt-predictions" {
    mutate {
      add_field => { "pipeline" => "belt-predictions" }
    }
  }
}

output {
  if [pipeline] == "belt-raw-data" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "belt-raw-data"
    }
  } else if [pipeline] == "belt-predictions" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "belt-predictions"
    }
  }

  stdout { codec => rubydebug }
}
